#1. Realizar un programa que lea cuatro valores numéricos e informar su suma
#y promedio.




num1 = int(input("cargar el primer numero: "))
num2 = int(input("cargar el segundo numero: "))
num3 = int(input("cargar el tercero numero: "))
num4 = int(input("cargar el cuarto numero: "))

suma = num1 + num2 + num3 + num4 
promedio = (suma/4)
promedio = int(promedio)
print  ("el promedio es:")
print (promedio)


